package sandbox.findbugs

/**
 * Created with IntelliJ IDEA.
 * User: Mirko
 * Date: 29.11.12
 * Time: 13:04
 * To change this template use File | Settings | File Templates.
 */
object BugType extends Enumeration {
  val
  DL_SYNCHRONIZATION_ON_BOOLEAN,
  DL_SYNCHRONIZATION_ON_BOXED_PRIMITIVE,
  DL_SYNCHRONIZATION_ON_SHARED_CONSTANT,
  DL_SYNCHRONIZATION_ON_UNSHARED_BOXED_PRIMITIVE,
  DMI_INVOKING_TOSTRING_ON_ARRAY,
  ES_COMPARING_STRINGS_WITH_EQ,
  ES_COMPARING_PARAMETER_STRING_WITH_EQ,
  MWN_MISMATCHED_NOTIFY,
  NP_STORE_INTO_NONNULL_FIELD,
  RC_REF_COMPARISON,
  RC_REF_COMPARISON_BAD_PRACTICE,
  RC_REF_COMPARISON_BAD_PRACTICE_BOOLEAN,
  RV_RETURN_VALUE_IGNORED,
  RV_RETURN_VALUE_IGNORED_BAD_PRACTICE,
  SA_FIELD_SELF_ASSIGNMENT,
  SA_FIELD_SELF_COMPARISON,
  SA_LOCAL_SELF_ASSIGNMENT,
  SA_LOCAL_SELF_ASSIGNMENT_INSTEAD_OF_FIELD,
  SQL_BAD_PREPARED_STATEMENT_ACCESS
  = Value
}
