package sae.analyses.architecture.hibernate

import unisson.model.impl.{GlobalOutgoingConstraint, GlobalIncomingConstraint}
import collection.mutable
import de.tud.cs.st.vespucci.interfaces.{IEnsemble, IConstraint}

/**
 *
 * @author Ralf Mitschke
 *
 */
object HibernateSlices
{


    object Hibernate_3_6_6
    {

        import HibernateEnsembles.Hibernate_3_6_6._

        val constraints: mutable.HashMap[String, mutable.HashSet[IConstraint]] = mutable.HashMap.empty


        val ensembles: mutable.HashMap[String, mutable.HashSet[IEnsemble]] = mutable.HashMap.empty

        ensembles("Actions.sad").add(Properties)
        ensembles("Actions.sad").add(EventFramework)
        ensembles("Actions.sad").add(SessionManagement)
        ensembles("Actions.sad").add(PersistenceManager)
        ensembles("Actions.sad").add(HQL)
        ensembles("Actions.sad").add(SQLStatements)
        ensembles("Actions.sad").add(DataTypes)
        ensembles("Actions.sad").add(Cache)
        ensembles("Actions.sad").add(JDBCStatementProcessing)
        ensembles("Actions.sad").add(Actions)
        ensembles("Actions.sad").add(HibernateUtilities)
        ensembles("Actions.sad").add(Statistics)
        ensembles("Actions.sad").add(Metadata)
        ensembles("Actions.sad").add(PropertySettings)
        ensembles("Actions.sad").add(SQLDialects)
        ensembles("Actions.sad").add(UserAPI)
        ensembles("Actions.sad").add(UtilitiesAndExceptions)
        ensembles("Annotations.sad").add(Cache)
        ensembles("Annotations.sad").add(Configuration)
        ensembles("Annotations.sad").add(HibernateORMapping)
        ensembles("Annotations.sad").add(Annotations)
        ensembles("BytecodeInstrumentation.sad").add(BytecodeInstrumentation)
        ensembles("BytecodeInstrumentation.sad").add(BytecodeInterception)
        ensembles("BytecodeInstrumentation.sad").add(BytecodeInstrumentationTool)
        ensembles("BytecodeInstrumentation.sad").add(PropertySettings)
        ensembles("BytecodeInstrumentation.sad").add(Proxies)
        ensembles("BytecodeInstrumentation.sad").add(UtilitiesAndExceptions)
        ensembles("BytecodeInstrumentation.sad").add(EntityRepresentation)
        ensembles("BytecodeInstrumentationTool.sad").add(BytecodeInstrumentation)
        ensembles("BytecodeInstrumentationTool.sad").add(EmptyEnsemble)
        ensembles("BytecodeInstrumentationTool.sad").add(BytecodeInstrumentationTool)
        ensembles("BytecodeInterception.sad").add(DataTypes)
        ensembles("BytecodeInterception.sad").add(BytecodeInstrumentation)
        ensembles("BytecodeInterception.sad").add(SessionManagement)
        ensembles("BytecodeInterception.sad").add(PersistenceManager)
        ensembles("BytecodeInterception.sad").add(EventFramework)
        ensembles("BytecodeInterception.sad").add(BytecodeInterception)
        ensembles("BytecodeInterception.sad").add(HibernateUtilities)
        ensembles("BytecodeInterception.sad").add(Proxies)
        ensembles("BytecodeInterception.sad").add(UtilitiesAndExceptions)
        ensembles("BytecodeInterception.sad").add(UserAPI)
        ensembles("BytecodeInterception.sad").add(EntityRepresentation)
        ensembles("Cache.sad").add(SessionManagement)
        ensembles("Cache.sad").add(PersistenceManager)
        ensembles("Cache.sad").add(EventFramework)
        ensembles("Cache.sad").add(HibernateORMapping)
        ensembles("Cache.sad").add(Annotations)
        ensembles("Cache.sad").add(ResultTransfomers)
        ensembles("Cache.sad").add(DataTypes)
        ensembles("Cache.sad").add(Cache)
        ensembles("Cache.sad").add(Configuration)
        ensembles("Cache.sad").add(Actions)
        ensembles("Cache.sad").add(HibernateUtilities)
        ensembles("Cache.sad").add(Statistics)
        ensembles("Cache.sad").add(PropertySettings)
        ensembles("Cache.sad").add(UserAPI)
        ensembles("Cache.sad").add(UtilitiesAndExceptions)
        ensembles("Configuration.sad").add(IdentifierGenerators)
        ensembles("Configuration.sad").add(EventFramework)
        ensembles("Configuration.sad").add(SessionManagement)
        ensembles("Configuration.sad").add(PersistenceManager)
        ensembles("Configuration.sad").add(HibernateORMapping)
        ensembles("Configuration.sad").add(SecurityPolicy)
        ensembles("Configuration.sad").add(Proxies)
        ensembles("Configuration.sad").add(Annotations)
        ensembles("Configuration.sad").add(EntityRepresentation)
        ensembles("Configuration.sad").add(SQLStatements)
        ensembles("Configuration.sad").add(JMX)
        ensembles("Configuration.sad").add(DataTypes)
        ensembles("Configuration.sad").add(Cache)
        ensembles("Configuration.sad").add(SchemaTool)
        ensembles("Configuration.sad").add(Configuration)
        ensembles("Configuration.sad").add(HibernateUtilities)
        ensembles("Configuration.sad").add(PropertySettings)
        ensembles("Configuration.sad").add(SQLDialects)
        ensembles("Configuration.sad").add(SchemaProcessing)
        ensembles("Configuration.sad").add(UserAPI)
        ensembles("Configuration.sad").add(UtilitiesAndExceptions)
        ensembles("ConnectionProvider.sad").add(Transactions)
        ensembles("ConnectionProvider.sad").add(ConnectionProvider)
        ensembles("ConnectionProvider.sad").add(SessionManagement)
        ensembles("ConnectionProvider.sad").add(JDBCStatementProcessing)
        ensembles("ConnectionProvider.sad").add(PropertySettings)
        ensembles("ConnectionProvider.sad").add(SchemaProcessing)
        ensembles("ConnectionProvider.sad").add(UtilitiesAndExceptions)
        ensembles("CriteriaExpressionFramework.sad").add(DataTypes)
        ensembles("CriteriaExpressionFramework.sad").add(SessionManagement)
        ensembles("CriteriaExpressionFramework.sad").add(PersistenceManager)
        ensembles("CriteriaExpressionFramework.sad").add(CriteriaExpressionFramework)
        ensembles("CriteriaExpressionFramework.sad").add(HibernateCriteria)
        ensembles("CriteriaExpressionFramework.sad").add(SQLDialects)
        ensembles("CriteriaExpressionFramework.sad").add(UtilitiesAndExceptions)
        ensembles("CriteriaExpressionFramework.sad").add(UserAPI)
        ensembles("CriteriaExpressionFramework.sad").add(ResultTransfomers)
        ensembles("DataTypes.sad").add(Properties)
        ensembles("DataTypes.sad").add(SessionManagement)
        ensembles("DataTypes.sad").add(PersistenceManager)
        ensembles("DataTypes.sad").add(HibernateORMapping)
        ensembles("DataTypes.sad").add(Proxies)
        ensembles("DataTypes.sad").add(EntityRepresentation)
        ensembles("DataTypes.sad").add(DataTypes)
        ensembles("DataTypes.sad").add(JDBCStatementProcessing)
        ensembles("DataTypes.sad").add(BytecodeInterception)
        ensembles("DataTypes.sad").add(PropertySettings)
        ensembles("DataTypes.sad").add(SQLDialects)
        ensembles("DataTypes.sad").add(UtilitiesAndExceptions)
        ensembles("DataTypes.sad").add(UserAPI)
        ensembles("DeprecatedUtility.sad").add(DeprecatedUtility)
        ensembles("DeprecatedUtility.sad").add(EmptyEnsemble)
        ensembles("DeprecatedUtility.sad").add(JDBCStatementProcessing)
        ensembles("EntityRepresentation.sad").add(IdentifierGenerators)
        ensembles("EntityRepresentation.sad").add(Properties)
        ensembles("EntityRepresentation.sad").add(SessionManagement)
        ensembles("EntityRepresentation.sad").add(PersistenceManager)
        ensembles("EntityRepresentation.sad").add(EventFramework)
        ensembles("EntityRepresentation.sad").add(HibernateORMapping)
        ensembles("EntityRepresentation.sad").add(Proxies)
        ensembles("EntityRepresentation.sad").add(EntityRepresentation)
        ensembles("EntityRepresentation.sad").add(BytecodeInstrumentation)
        ensembles("EntityRepresentation.sad").add(DataTypes)
        ensembles("EntityRepresentation.sad").add(BytecodeInterception)
        ensembles("EntityRepresentation.sad").add(HibernateUtilities)
        ensembles("EntityRepresentation.sad").add(PropertySettings)
        ensembles("EntityRepresentation.sad").add(UserAPI)
        ensembles("EntityRepresentation.sad").add(UtilitiesAndExceptions)
        ensembles("EventFramework.sad").add(IdentifierGenerators)
        ensembles("EventFramework.sad").add(EventFramework)
        ensembles("EventFramework.sad").add(SessionManagement)
        ensembles("EventFramework.sad").add(PersistenceManager)
        ensembles("EventFramework.sad").add(SecurityPolicy)
        ensembles("EventFramework.sad").add(Proxies)
        ensembles("EventFramework.sad").add(HQL)
        ensembles("EventFramework.sad").add(EntityRepresentation)
        ensembles("EventFramework.sad").add(SQLStatements)
        ensembles("EventFramework.sad").add(DataTypes)
        ensembles("EventFramework.sad").add(Cache)
        ensembles("EventFramework.sad").add(JDBCStatementProcessing)
        ensembles("EventFramework.sad").add(Configuration)
        ensembles("EventFramework.sad").add(BytecodeInterception)
        ensembles("EventFramework.sad").add(Actions)
        ensembles("EventFramework.sad").add(HibernateUtilities)
        ensembles("EventFramework.sad").add(Statistics)
        ensembles("EventFramework.sad").add(HibernateClassic)
        ensembles("EventFramework.sad").add(PropertySettings)
        ensembles("EventFramework.sad").add(HQL_Legacy)
        ensembles("EventFramework.sad").add(SQLDialects)
        ensembles("EventFramework.sad").add(UserAPI)
        ensembles("EventFramework.sad").add(UtilitiesAndExceptions)
        ensembles("HandwrittenSQLLoader.sad").add(SQLStatements)
        ensembles("HandwrittenSQLLoader.sad").add(DataTypes)
        ensembles("HandwrittenSQLLoader.sad").add(SessionManagement)
        ensembles("HandwrittenSQLLoader.sad").add(PersistenceManager)
        ensembles("HandwrittenSQLLoader.sad").add(HandwrittenSQLLoader)
        ensembles("HandwrittenSQLLoader.sad").add(PropertySettings)
        ensembles("HandwrittenSQLLoader.sad").add(SQLDialects)
        ensembles("HandwrittenSQLLoader.sad").add(UtilitiesAndExceptions)
        ensembles("HandwrittenSQLLoader.sad").add(UserAPI)
        ensembles("HandwrittenSQLLoader.sad").add(ResultTransfomers)
        ensembles("HibernateClassic.sad").add(JMX)
        ensembles("HibernateClassic.sad").add(DataTypes)
        ensembles("HibernateClassic.sad").add(SessionManagement)
        ensembles("HibernateClassic.sad").add(EventFramework)
        ensembles("HibernateClassic.sad").add(HibernateClassic)
        ensembles("HibernateClassic.sad").add(UtilitiesAndExceptions)
        ensembles("HibernateClassic.sad").add(UserAPI)
        ensembles("HibernateClassic.sad").add(EntityRepresentation)
        ensembles("HibernateCriteria.sad").add(DataTypes)
        ensembles("HibernateCriteria.sad").add(SessionManagement)
        ensembles("HibernateCriteria.sad").add(PersistenceManager)
        ensembles("HibernateCriteria.sad").add(HibernateUtilities)
        ensembles("HibernateCriteria.sad").add(CriteriaExpressionFramework)
        ensembles("HibernateCriteria.sad").add(HibernateCriteria)
        ensembles("HibernateCriteria.sad").add(SQLDialects)
        ensembles("HibernateCriteria.sad").add(UtilitiesAndExceptions)
        ensembles("HibernateCriteria.sad").add(HQL)
        ensembles("HibernateCriteria.sad").add(UserAPI)
        ensembles("HibernateCriteria.sad").add(ResultTransfomers)
        ensembles("HibernateORMapping.sad").add(IdentifierGenerators)
        ensembles("HibernateORMapping.sad").add(Properties)
        ensembles("HibernateORMapping.sad").add(SessionManagement)
        ensembles("HibernateORMapping.sad").add(PersistenceManager)
        ensembles("HibernateORMapping.sad").add(HibernateORMapping)
        ensembles("HibernateORMapping.sad").add(Annotations)
        ensembles("HibernateORMapping.sad").add(EntityRepresentation)
        ensembles("HibernateORMapping.sad").add(SQLStatements)
        ensembles("HibernateORMapping.sad").add(DataTypes)
        ensembles("HibernateORMapping.sad").add(Cache)
        ensembles("HibernateORMapping.sad").add(Configuration)
        ensembles("HibernateORMapping.sad").add(HibernateUtilities)
        ensembles("HibernateORMapping.sad").add(SQLDialects)
        ensembles("HibernateORMapping.sad").add(SchemaProcessing)
        ensembles("HibernateORMapping.sad").add(UtilitiesAndExceptions)
        ensembles("HibernateUtilities.sad").add(IdentifierGenerators)
        ensembles("HibernateUtilities.sad").add(Properties)
        ensembles("HibernateUtilities.sad").add(EventFramework)
        ensembles("HibernateUtilities.sad").add(SessionManagement)
        ensembles("HibernateUtilities.sad").add(PersistenceManager)
        ensembles("HibernateUtilities.sad").add(HibernateORMapping)
        ensembles("HibernateUtilities.sad").add(HibernateCriteria)
        ensembles("HibernateUtilities.sad").add(EntityRepresentation)
        ensembles("HibernateUtilities.sad").add(HQL)
        ensembles("HibernateUtilities.sad").add(SQLStatements)
        ensembles("HibernateUtilities.sad").add(JMX)
        ensembles("HibernateUtilities.sad").add(DataTypes)
        ensembles("HibernateUtilities.sad").add(Cache)
        ensembles("HibernateUtilities.sad").add(Configuration)
        ensembles("HibernateUtilities.sad").add(BytecodeInterception)
        ensembles("HibernateUtilities.sad").add(Actions)
        ensembles("HibernateUtilities.sad").add(HibernateUtilities)
        ensembles("HibernateUtilities.sad").add(Metadata)
        ensembles("HibernateUtilities.sad").add(PropertySettings)
        ensembles("HibernateUtilities.sad").add(SQLDialects)
        ensembles("HibernateUtilities.sad").add(UserAPI)
        ensembles("HibernateUtilities.sad").add(UtilitiesAndExceptions)
        ensembles("HQL_Legacy.sad").add(DataTypes)
        ensembles("HQL_Legacy.sad").add(SessionManagement)
        ensembles("HQL_Legacy.sad").add(PersistenceManager)
        ensembles("HQL_Legacy.sad").add(EventFramework)
        ensembles("HQL_Legacy.sad").add(Statistics)
        ensembles("HQL_Legacy.sad").add(HQL_Legacy)
        ensembles("HQL_Legacy.sad").add(SQLDialects)
        ensembles("HQL_Legacy.sad").add(UtilitiesAndExceptions)
        ensembles("HQL_Legacy.sad").add(HQL)
        ensembles("HQL_Legacy.sad").add(UserAPI)
        ensembles("HQL_Legacy.sad").add(EntityRepresentation)
        ensembles("HQL_Legacy.sad").add(ResultTransfomers)
        ensembles("HQL.sad").add(IdentifierGenerators)
        ensembles("HQL.sad").add(EventFramework)
        ensembles("HQL.sad").add(SessionManagement)
        ensembles("HQL.sad").add(PersistenceManager)
        ensembles("HQL.sad").add(HibernateCriteria)
        ensembles("HQL.sad").add(HQL)
        ensembles("HQL.sad").add(EntityRepresentation)
        ensembles("HQL.sad").add(ResultTransfomers)
        ensembles("HQL.sad").add(SQLStatements)
        ensembles("HQL.sad").add(Transactions)
        ensembles("HQL.sad").add(DataTypes)
        ensembles("HQL.sad").add(JDBCStatementProcessing)
        ensembles("HQL.sad").add(Actions)
        ensembles("HQL.sad").add(HibernateUtilities)
        ensembles("HQL.sad").add(Statistics)
        ensembles("HQL.sad").add(PropertySettings)
        ensembles("HQL.sad").add(HQL_Legacy)
        ensembles("HQL.sad").add(SQLDialects)
        ensembles("HQL.sad").add(UserAPI)
        ensembles("HQL.sad").add(UtilitiesAndExceptions)
        ensembles("IdentifierGenerators.sad").add(IdentifierGenerators)
        ensembles("IdentifierGenerators.sad").add(EventFramework)
        ensembles("IdentifierGenerators.sad").add(SessionManagement)
        ensembles("IdentifierGenerators.sad").add(PersistenceManager)
        ensembles("IdentifierGenerators.sad").add(HibernateORMapping)
        ensembles("IdentifierGenerators.sad").add(HQL)
        ensembles("IdentifierGenerators.sad").add(EntityRepresentation)
        ensembles("IdentifierGenerators.sad").add(SQLStatements)
        ensembles("IdentifierGenerators.sad").add(Transactions)
        ensembles("IdentifierGenerators.sad").add(JMX)
        ensembles("IdentifierGenerators.sad").add(DataTypes)
        ensembles("IdentifierGenerators.sad").add(JDBCStatementProcessing)
        ensembles("IdentifierGenerators.sad").add(Configuration)
        ensembles("IdentifierGenerators.sad").add(HibernateUtilities)
        ensembles("IdentifierGenerators.sad").add(SQLDialects)
        ensembles("IdentifierGenerators.sad").add(UserAPI)
        ensembles("IdentifierGenerators.sad").add(UtilitiesAndExceptions)
        ensembles("JDBCStatementProcessing.sad").add(IdentifierGenerators)
        ensembles("JDBCStatementProcessing.sad").add(EventFramework)
        ensembles("JDBCStatementProcessing.sad").add(SessionManagement)
        ensembles("JDBCStatementProcessing.sad").add(PersistenceManager)
        ensembles("JDBCStatementProcessing.sad").add(HQL)
        ensembles("JDBCStatementProcessing.sad").add(SQLStatements)
        ensembles("JDBCStatementProcessing.sad").add(Transactions)
        ensembles("JDBCStatementProcessing.sad").add(ConnectionProvider)
        ensembles("JDBCStatementProcessing.sad").add(DeprecatedUtility)
        ensembles("JDBCStatementProcessing.sad").add(DataTypes)
        ensembles("JDBCStatementProcessing.sad").add(JDBCStatementProcessing)
        ensembles("JDBCStatementProcessing.sad").add(Actions)
        ensembles("JDBCStatementProcessing.sad").add(Statistics)
        ensembles("JDBCStatementProcessing.sad").add(PropertySettings)
        ensembles("JDBCStatementProcessing.sad").add(SQLDialects)
        ensembles("JDBCStatementProcessing.sad").add(SchemaProcessing)
        ensembles("JDBCStatementProcessing.sad").add(UserAPI)
        ensembles("JDBCStatementProcessing.sad").add(UtilitiesAndExceptions)
        ensembles("JMX.sad").add(JMX)
        ensembles("JMX.sad").add(EmptyEnsemble)
        ensembles("Metadata.sad").add(DataTypes)
        ensembles("Metadata.sad").add(SessionManagement)
        ensembles("Metadata.sad").add(Metadata)
        ensembles("Metadata.sad").add(UtilitiesAndExceptions)
        ensembles("Properties.sad").add(DataTypes)
        ensembles("Properties.sad").add(Properties)
        ensembles("Properties.sad").add(SessionManagement)
        ensembles("Properties.sad").add(PersistenceManager)
        ensembles("Properties.sad").add(HibernateORMapping)
        ensembles("Properties.sad").add(HibernateUtilities)
        ensembles("Properties.sad").add(UtilitiesAndExceptions)
        ensembles("Properties.sad").add(EntityRepresentation)
        ensembles("Properties.sad").add(ResultTransfomers)
        ensembles("PropertySettings.sad").add(EventFramework)
        ensembles("PropertySettings.sad").add(SessionManagement)
        ensembles("PropertySettings.sad").add(PersistenceManager)
        ensembles("PropertySettings.sad").add(HandwrittenSQLLoader)
        ensembles("PropertySettings.sad").add(HQL)
        ensembles("PropertySettings.sad").add(EntityRepresentation)
        ensembles("PropertySettings.sad").add(Transactions)
        ensembles("PropertySettings.sad").add(ConnectionProvider)
        ensembles("PropertySettings.sad").add(BytecodeInstrumentation)
        ensembles("PropertySettings.sad").add(DataTypes)
        ensembles("PropertySettings.sad").add(Cache)
        ensembles("PropertySettings.sad").add(JDBCStatementProcessing)
        ensembles("PropertySettings.sad").add(Configuration)
        ensembles("PropertySettings.sad").add(Actions)
        ensembles("PropertySettings.sad").add(HibernateUtilities)
        ensembles("PropertySettings.sad").add(PropertySettings)
        ensembles("PropertySettings.sad").add(SQLDialects)
        ensembles("PropertySettings.sad").add(SchemaProcessing)
        ensembles("PropertySettings.sad").add(UserAPI)
        ensembles("PropertySettings.sad").add(UtilitiesAndExceptions)
        ensembles("Proxies.sad").add(DataTypes)
        ensembles("Proxies.sad").add(BytecodeInstrumentation)
        ensembles("Proxies.sad").add(SessionManagement)
        ensembles("Proxies.sad").add(PersistenceManager)
        ensembles("Proxies.sad").add(EventFramework)
        ensembles("Proxies.sad").add(Configuration)
        ensembles("Proxies.sad").add(BytecodeInterception)
        ensembles("Proxies.sad").add(Proxies)
        ensembles("Proxies.sad").add(UtilitiesAndExceptions)
        ensembles("Proxies.sad").add(UserAPI)
        ensembles("Proxies.sad").add(EntityRepresentation)
        ensembles("ResultTransfomers.sad").add(Cache)
        ensembles("ResultTransfomers.sad").add(Properties)
        ensembles("ResultTransfomers.sad").add(PersistenceManager)
        ensembles("ResultTransfomers.sad").add(HandwrittenSQLLoader)
        ensembles("ResultTransfomers.sad").add(CriteriaExpressionFramework)
        ensembles("ResultTransfomers.sad").add(HQL_Legacy)
        ensembles("ResultTransfomers.sad").add(HibernateCriteria)
        ensembles("ResultTransfomers.sad").add(UtilitiesAndExceptions)
        ensembles("ResultTransfomers.sad").add(HQL)
        ensembles("ResultTransfomers.sad").add(UserAPI)
        ensembles("ResultTransfomers.sad").add(ResultTransfomers)
        ensembles("SchemaProcessing.sad").add(ConnectionProvider)
        ensembles("SchemaProcessing.sad").add(JDBCStatementProcessing)
        ensembles("SchemaProcessing.sad").add(Configuration)
        ensembles("SchemaProcessing.sad").add(HibernateORMapping)
        ensembles("SchemaProcessing.sad").add(PropertySettings)
        ensembles("SchemaProcessing.sad").add(SQLDialects)
        ensembles("SchemaProcessing.sad").add(SchemaProcessing)
        ensembles("SchemaProcessing.sad").add(UtilitiesAndExceptions)
        ensembles("SchemaTool.sad").add(EmptyEnsemble)
        ensembles("SchemaTool.sad").add(Configuration)
        ensembles("SchemaTool.sad").add(SchemaTool)
        ensembles("SchemaTool.sad").add(SchemaProcessing)
        ensembles("SchemaTool.sad").add(UtilitiesAndExceptions)
        ensembles("SecurityPolicy.sad").add(PersistenceManager)
        ensembles("SecurityPolicy.sad").add(EventFramework)
        ensembles("SecurityPolicy.sad").add(Configuration)
        ensembles("SecurityPolicy.sad").add(SecurityPolicy)
        ensembles("SecurityPolicy.sad").add(UtilitiesAndExceptions)
        ensembles("SQLDialects.sad").add(IdentifierGenerators)
        ensembles("SQLDialects.sad").add(EventFramework)
        ensembles("SQLDialects.sad").add(SessionManagement)
        ensembles("SQLDialects.sad").add(PersistenceManager)
        ensembles("SQLDialects.sad").add(HandwrittenSQLLoader)
        ensembles("SQLDialects.sad").add(HibernateORMapping)
        ensembles("SQLDialects.sad").add(CriteriaExpressionFramework)
        ensembles("SQLDialects.sad").add(HibernateCriteria)
        ensembles("SQLDialects.sad").add(HQL)
        ensembles("SQLDialects.sad").add(SQLStatements)
        ensembles("SQLDialects.sad").add(DataTypes)
        ensembles("SQLDialects.sad").add(JDBCStatementProcessing)
        ensembles("SQLDialects.sad").add(Configuration)
        ensembles("SQLDialects.sad").add(Actions)
        ensembles("SQLDialects.sad").add(HibernateUtilities)
        ensembles("SQLDialects.sad").add(Statistics)
        ensembles("SQLDialects.sad").add(PropertySettings)
        ensembles("SQLDialects.sad").add(HQL_Legacy)
        ensembles("SQLDialects.sad").add(SQLDialects)
        ensembles("SQLDialects.sad").add(SchemaProcessing)
        ensembles("SQLDialects.sad").add(UserAPI)
        ensembles("SQLDialects.sad").add(UtilitiesAndExceptions)
        ensembles("SQLStatements.sad").add(IdentifierGenerators)
        ensembles("SQLStatements.sad").add(SessionManagement)
        ensembles("SQLStatements.sad").add(PersistenceManager)
        ensembles("SQLStatements.sad").add(EventFramework)
        ensembles("SQLStatements.sad").add(HandwrittenSQLLoader)
        ensembles("SQLStatements.sad").add(HibernateORMapping)
        ensembles("SQLStatements.sad").add(HQL)
        ensembles("SQLStatements.sad").add(SQLStatements)
        ensembles("SQLStatements.sad").add(DataTypes)
        ensembles("SQLStatements.sad").add(JDBCStatementProcessing)
        ensembles("SQLStatements.sad").add(Configuration)
        ensembles("SQLStatements.sad").add(Actions)
        ensembles("SQLStatements.sad").add(HibernateUtilities)
        ensembles("SQLStatements.sad").add(SQLDialects)
        ensembles("SQLStatements.sad").add(UserAPI)
        ensembles("SQLStatements.sad").add(UtilitiesAndExceptions)
        ensembles("Statistics.sad").add(SessionManagement)
        ensembles("Statistics.sad").add(PersistenceManager)
        ensembles("Statistics.sad").add(EventFramework)
        ensembles("Statistics.sad").add(HQL)
        ensembles("Statistics.sad").add(JMX)
        ensembles("Statistics.sad").add(DataTypes)
        ensembles("Statistics.sad").add(Cache)
        ensembles("Statistics.sad").add(JDBCStatementProcessing)
        ensembles("Statistics.sad").add(Actions)
        ensembles("Statistics.sad").add(Statistics)
        ensembles("Statistics.sad").add(HQL_Legacy)
        ensembles("Statistics.sad").add(SQLDialects)
        ensembles("Statistics.sad").add(UtilitiesAndExceptions)
        ensembles("Transactions.sad").add(IdentifierGenerators)
        ensembles("Transactions.sad").add(Transactions)
        ensembles("Transactions.sad").add(ConnectionProvider)
        ensembles("Transactions.sad").add(SessionManagement)
        ensembles("Transactions.sad").add(JDBCStatementProcessing)
        ensembles("Transactions.sad").add(PropertySettings)
        ensembles("Transactions.sad").add(UtilitiesAndExceptions)
        ensembles("Transactions.sad").add(HQL)
        ensembles("Transactions.sad").add(UserAPI)
        ensembles("UtilitiesAndExceptions.sad").add(DataTypes)
        ensembles("UtilitiesAndExceptions.sad").add(Properties)
        ensembles("UtilitiesAndExceptions.sad").add(SessionManagement)
        ensembles("UtilitiesAndExceptions.sad").add(PersistenceManager)
        ensembles("UtilitiesAndExceptions.sad").add(Configuration)
        ensembles("UtilitiesAndExceptions.sad").add(HibernateUtilities)
        ensembles("UtilitiesAndExceptions.sad").add(SQLDialects)
        ensembles("UtilitiesAndExceptions.sad").add(UtilitiesAndExceptions)
        ensembles("UtilitiesAndExceptions.sad").add(UserAPI)


        /**
         * Adding all constraints
         */
        // ^\s*(.*\.sad);(.*?);(.*?);(.*?);(.*)
        // constraints("$1").add($2("$3", $4, $5))
        constraints("Actions.sad").add(GlobalIncomingConstraint("all", SessionManagement, Actions))
        constraints("Actions.sad").add(GlobalIncomingConstraint("all", SQLDialects, Actions))
        constraints("Actions.sad").add(GlobalIncomingConstraint("all", PersistenceManager, Actions))
        constraints("Actions.sad").add(GlobalIncomingConstraint("all", SQLStatements, Actions))
        constraints("Actions.sad").add(GlobalIncomingConstraint("all", HQL, Actions))
        constraints("Actions.sad").add(GlobalOutgoingConstraint("all", Actions, UtilitiesAndExceptions))
        constraints("Actions.sad").add(GlobalOutgoingConstraint("all", Actions, DataTypes))
        constraints("Actions.sad").add(GlobalOutgoingConstraint("all", Actions, HibernateUtilities))
        constraints("Actions.sad").add(GlobalOutgoingConstraint("all", Actions, Statistics))
        constraints("Actions.sad").add(GlobalIncomingConstraint("all", EventFramework, Actions))
        constraints("Actions.sad").add(GlobalOutgoingConstraint("all", Actions, EventFramework))
        constraints("Actions.sad").add(GlobalOutgoingConstraint("all", Actions, PersistenceManager))
        constraints("Actions.sad").add(GlobalOutgoingConstraint("all", Actions, Metadata))
        constraints("Actions.sad").add(GlobalOutgoingConstraint("all", Actions, SessionManagement))
        constraints("Actions.sad").add(GlobalOutgoingConstraint("all", Actions, Cache))
        constraints("Actions.sad").add(GlobalOutgoingConstraint("all", Actions, JDBCStatementProcessing))
        constraints("Actions.sad").add(GlobalOutgoingConstraint("all", Actions, UserAPI))
        constraints("Actions.sad").add(GlobalOutgoingConstraint("all", Actions, PropertySettings))
        constraints("Annotations.sad").add(GlobalOutgoingConstraint("all", Annotations, Cache))
        constraints("Annotations.sad").add(GlobalIncomingConstraint("all", Configuration, Annotations))
        constraints("Annotations.sad").add(GlobalIncomingConstraint("all", HibernateORMapping, Annotations))
        constraints("BytecodeInstrumentation.sad")
                .add(GlobalIncomingConstraint("all", BytecodeInstrumentationTool, BytecodeInstrumentation))
        constraints("BytecodeInstrumentation.sad")
                .add(GlobalOutgoingConstraint("all", BytecodeInstrumentation, UtilitiesAndExceptions))
        constraints("BytecodeInstrumentation.sad")
                .add(GlobalOutgoingConstraint("all", BytecodeInstrumentation, Proxies))
        constraints("BytecodeInstrumentation.sad")
                .add(GlobalIncomingConstraint("all", EntityRepresentation, BytecodeInstrumentation))
        constraints("BytecodeInstrumentation.sad")
                .add(GlobalIncomingConstraint("all", PropertySettings, BytecodeInstrumentation))
        constraints("BytecodeInstrumentation.sad")
                .add(GlobalIncomingConstraint("all", BytecodeInterception, BytecodeInstrumentation))
        constraints("BytecodeInstrumentationTool.sad")
                .add(GlobalOutgoingConstraint("all", BytecodeInstrumentationTool, BytecodeInstrumentation))
        constraints("BytecodeInstrumentationTool.sad")
                .add(GlobalIncomingConstraint("all", EmptyEnsemble, BytecodeInstrumentationTool))
        constraints("BytecodeInterception.sad").add(GlobalIncomingConstraint("all", UserAPI, BytecodeInterception))
        constraints("BytecodeInterception.sad")
                .add(GlobalIncomingConstraint("all", EntityRepresentation, BytecodeInterception))
        constraints("BytecodeInterception.sad")
                .add(GlobalIncomingConstraint("all", EventFramework, BytecodeInterception))
        constraints("BytecodeInterception.sad")
                .add(GlobalIncomingConstraint("all", HibernateUtilities, BytecodeInterception))
        constraints("BytecodeInterception.sad").add(GlobalOutgoingConstraint("all", BytecodeInterception, Proxies))
        constraints("BytecodeInterception.sad")
                .add(GlobalOutgoingConstraint("all", BytecodeInterception, SessionManagement))
        constraints("BytecodeInterception.sad")
                .add(GlobalOutgoingConstraint("all", BytecodeInterception, BytecodeInstrumentation))
        constraints("BytecodeInterception.sad")
                .add(GlobalOutgoingConstraint("all", BytecodeInterception, UtilitiesAndExceptions))
        constraints("BytecodeInterception.sad")
                .add(GlobalIncomingConstraint("all", PersistenceManager, BytecodeInterception))
        constraints("BytecodeInterception.sad").add(GlobalIncomingConstraint("all", DataTypes, BytecodeInterception))
        constraints("Cache.sad").add(GlobalIncomingConstraint("all", SessionManagement, Cache))
        constraints("Cache.sad").add(GlobalIncomingConstraint("all", Configuration, Cache))
        constraints("Cache.sad").add(GlobalIncomingConstraint("all", PropertySettings, Cache))
        constraints("Cache.sad").add(GlobalIncomingConstraint("all", PersistenceManager, Cache))
        constraints("Cache.sad").add(GlobalIncomingConstraint("all", Annotations, Cache))
        constraints("Cache.sad").add(GlobalIncomingConstraint("all", Statistics, Cache))
        constraints("Cache.sad").add(GlobalIncomingConstraint("all", Actions, Cache))
        constraints("Cache.sad").add(GlobalIncomingConstraint("all", EventFramework, Cache))
        constraints("Cache.sad").add(GlobalOutgoingConstraint("all", Cache, ResultTransfomers))
        constraints("Cache.sad").add(GlobalOutgoingConstraint("all", Cache, PersistenceManager))
        constraints("Cache.sad").add(GlobalOutgoingConstraint("all", Cache, SessionManagement))
        constraints("Cache.sad").add(GlobalOutgoingConstraint("all", Cache, UtilitiesAndExceptions))
        constraints("Cache.sad").add(GlobalOutgoingConstraint("all", Cache, UserAPI))
        constraints("Cache.sad").add(GlobalOutgoingConstraint("all", Cache, DataTypes))
        constraints("Cache.sad").add(GlobalOutgoingConstraint("all", Cache, PropertySettings))
        constraints("Cache.sad").add(GlobalOutgoingConstraint("all", Cache, HibernateUtilities))
        constraints("Cache.sad").add(GlobalOutgoingConstraint("all", Cache, EventFramework))
        constraints("Cache.sad").add(GlobalOutgoingConstraint("all", Cache, HibernateORMapping))
        constraints("Configuration.sad").add(GlobalIncomingConstraint("all", SecurityPolicy, Configuration))
        constraints("Configuration.sad").add(GlobalIncomingConstraint("all", JMX, Configuration))
        constraints("Configuration.sad").add(GlobalIncomingConstraint("all", HibernateORMapping, Configuration))
        constraints("Configuration.sad").add(GlobalIncomingConstraint("all", UtilitiesAndExceptions, Configuration))
        constraints("Configuration.sad").add(GlobalIncomingConstraint("all", EventFramework, Configuration))
        constraints("Configuration.sad").add(GlobalIncomingConstraint("all", HibernateUtilities, Configuration))
        constraints("Configuration.sad").add(GlobalIncomingConstraint("all", SchemaTool, Configuration))
        constraints("Configuration.sad").add(GlobalIncomingConstraint("all", SessionManagement, Configuration))
        constraints("Configuration.sad").add(GlobalOutgoingConstraint("all", Configuration, IdentifierGenerators))
        constraints("Configuration.sad").add(GlobalOutgoingConstraint("all", Configuration, EventFramework))
        constraints("Configuration.sad").add(GlobalOutgoingConstraint("all", Configuration, PropertySettings))
        constraints("Configuration.sad").add(GlobalOutgoingConstraint("all", Configuration, SQLDialects))
        constraints("Configuration.sad").add(GlobalOutgoingConstraint("all", Configuration, EntityRepresentation))
        constraints("Configuration.sad").add(GlobalOutgoingConstraint("all", Configuration, SecurityPolicy))
        constraints("Configuration.sad").add(GlobalOutgoingConstraint("all", Configuration, SchemaProcessing))
        constraints("Configuration.sad").add(GlobalOutgoingConstraint("all", Configuration, UserAPI))
        constraints("Configuration.sad").add(GlobalOutgoingConstraint("all", Configuration, DataTypes))
        constraints("Configuration.sad").add(GlobalOutgoingConstraint("all", Configuration, Cache))
        constraints("Configuration.sad").add(GlobalOutgoingConstraint("all", Configuration, PersistenceManager))
        constraints("Configuration.sad").add(GlobalOutgoingConstraint("all", Configuration, HibernateORMapping))
        constraints("Configuration.sad").add(GlobalOutgoingConstraint("all", Configuration, Proxies))
        constraints("Configuration.sad").add(GlobalOutgoingConstraint("all", Configuration, Annotations))
        constraints("Configuration.sad").add(GlobalOutgoingConstraint("all", Configuration, HibernateUtilities))
        constraints("Configuration.sad").add(GlobalOutgoingConstraint("all", Configuration, SessionManagement))
        constraints("Configuration.sad").add(GlobalOutgoingConstraint("all", Configuration, SQLStatements))
        constraints("Configuration.sad").add(GlobalOutgoingConstraint("all", Configuration, UtilitiesAndExceptions))
        constraints("Configuration.sad").add(GlobalIncomingConstraint("all", PersistenceManager, Configuration))
        constraints("Configuration.sad").add(GlobalIncomingConstraint("all", SchemaProcessing, Configuration))
        constraints("ConnectionProvider.sad")
                .add(GlobalIncomingConstraint("all", SessionManagement, ConnectionProvider))
        constraints("ConnectionProvider.sad")
                .add(GlobalIncomingConstraint("all", JDBCStatementProcessing, ConnectionProvider))
        constraints("ConnectionProvider.sad")
                .add(GlobalOutgoingConstraint("all", ConnectionProvider, UtilitiesAndExceptions))
        constraints("ConnectionProvider.sad").add(GlobalOutgoingConstraint("all", ConnectionProvider, PropertySettings))
        constraints("ConnectionProvider.sad").add(GlobalIncomingConstraint("all", PropertySettings, ConnectionProvider))
        constraints("ConnectionProvider.sad").add(GlobalIncomingConstraint("all", Transactions, ConnectionProvider))
        constraints("ConnectionProvider.sad").add(GlobalIncomingConstraint("all", SchemaProcessing, ConnectionProvider))
        constraints("CriteriaExpressionFramework.sad")
                .add(GlobalIncomingConstraint("all", HibernateCriteria, CriteriaExpressionFramework))
        constraints("CriteriaExpressionFramework.sad")
                .add(GlobalIncomingConstraint("all", UserAPI, CriteriaExpressionFramework))
        constraints("CriteriaExpressionFramework.sad")
                .add(GlobalOutgoingConstraint("all", CriteriaExpressionFramework, HibernateCriteria))
        constraints("CriteriaExpressionFramework.sad")
                .add(GlobalOutgoingConstraint("all", CriteriaExpressionFramework, ResultTransfomers))
        constraints("CriteriaExpressionFramework.sad")
                .add(GlobalOutgoingConstraint("all", CriteriaExpressionFramework, DataTypes))
        constraints("CriteriaExpressionFramework.sad")
                .add(GlobalOutgoingConstraint("all", CriteriaExpressionFramework, UtilitiesAndExceptions))
        constraints("CriteriaExpressionFramework.sad")
                .add(GlobalOutgoingConstraint("all", CriteriaExpressionFramework, PersistenceManager))
        constraints("CriteriaExpressionFramework.sad")
                .add(GlobalOutgoingConstraint("all", CriteriaExpressionFramework, UserAPI))
        constraints("CriteriaExpressionFramework.sad")
                .add(GlobalOutgoingConstraint("all", CriteriaExpressionFramework, SQLDialects))
        constraints("CriteriaExpressionFramework.sad")
                .add(GlobalOutgoingConstraint("all", CriteriaExpressionFramework, SessionManagement))
        constraints("DataTypes.sad").add(GlobalOutgoingConstraint("all", DataTypes, UtilitiesAndExceptions))
        constraints("DataTypes.sad").add(GlobalOutgoingConstraint("all", DataTypes, PersistenceManager))
        constraints("DataTypes.sad").add(GlobalOutgoingConstraint("all", DataTypes, EntityRepresentation))
        constraints("DataTypes.sad").add(GlobalOutgoingConstraint("all", DataTypes, JDBCStatementProcessing))
        constraints("DataTypes.sad").add(GlobalOutgoingConstraint("all", DataTypes, HibernateORMapping))
        constraints("DataTypes.sad").add(GlobalOutgoingConstraint("all", DataTypes, SQLDialects))
        constraints("DataTypes.sad").add(GlobalOutgoingConstraint("all", DataTypes, BytecodeInterception))
        constraints("DataTypes.sad").add(GlobalOutgoingConstraint("all", DataTypes, PropertySettings))
        constraints("DataTypes.sad").add(GlobalOutgoingConstraint("all", DataTypes, UserAPI))
        constraints("DataTypes.sad").add(GlobalOutgoingConstraint("all", DataTypes, SessionManagement))
        constraints("DataTypes.sad").add(GlobalOutgoingConstraint("all", DataTypes, Properties))
        constraints("DataTypes.sad").add(GlobalOutgoingConstraint("all", DataTypes, Proxies))
        constraints("DeprecatedUtility.sad")
                .add(GlobalIncomingConstraint("all", JDBCStatementProcessing, DeprecatedUtility))
        constraints("DeprecatedUtility.sad").add(GlobalOutgoingConstraint("all", DeprecatedUtility, EmptyEnsemble))
        constraints("EntityRepresentation.sad")
                .add(GlobalOutgoingConstraint("all", EntityRepresentation, IdentifierGenerators))
        constraints("EntityRepresentation.sad").add(GlobalOutgoingConstraint("all", EntityRepresentation, Properties))
        constraints("EntityRepresentation.sad")
                .add(GlobalOutgoingConstraint("all", EntityRepresentation, UtilitiesAndExceptions))
        constraints("EntityRepresentation.sad")
                .add(GlobalOutgoingConstraint("all", EntityRepresentation, HibernateORMapping))
        constraints("EntityRepresentation.sad")
                .add(GlobalOutgoingConstraint("all", EntityRepresentation, PropertySettings))
        constraints("EntityRepresentation.sad").add(GlobalOutgoingConstraint("all", EntityRepresentation, DataTypes))
        constraints("EntityRepresentation.sad").add(GlobalOutgoingConstraint("all", EntityRepresentation, UserAPI))
        constraints("EntityRepresentation.sad")
                .add(GlobalOutgoingConstraint("all", EntityRepresentation, PersistenceManager))
        constraints("EntityRepresentation.sad")
                .add(GlobalOutgoingConstraint("all", EntityRepresentation, BytecodeInstrumentation))
        constraints("EntityRepresentation.sad")
                .add(GlobalOutgoingConstraint("all", EntityRepresentation, HibernateUtilities))
        constraints("EntityRepresentation.sad")
                .add(GlobalOutgoingConstraint("all", EntityRepresentation, BytecodeInterception))
        constraints("EntityRepresentation.sad")
                .add(GlobalOutgoingConstraint("all", EntityRepresentation, SessionManagement))
        constraints("EntityRepresentation.sad")
                .add(GlobalOutgoingConstraint("all", EntityRepresentation, EventFramework))
        constraints("EntityRepresentation.sad").add(GlobalOutgoingConstraint("all", EntityRepresentation, Proxies))
        constraints("EventFramework.sad").add(GlobalIncomingConstraint("all", SecurityPolicy, EventFramework))
        constraints("EventFramework.sad").add(GlobalIncomingConstraint("all", EntityRepresentation, EventFramework))
        constraints("EventFramework.sad").add(GlobalIncomingConstraint("all", SQLStatements, EventFramework))
        constraints("EventFramework.sad").add(GlobalIncomingConstraint("all", HQL_Legacy, EventFramework))
        constraints("EventFramework.sad").add(GlobalOutgoingConstraint("all", EventFramework, BytecodeInterception))
        constraints("EventFramework.sad").add(GlobalOutgoingConstraint("all", EventFramework, Cache))
        constraints("EventFramework.sad").add(GlobalOutgoingConstraint("all", EventFramework, UtilitiesAndExceptions))
        constraints("EventFramework.sad").add(GlobalOutgoingConstraint("all", EventFramework, Actions))
        constraints("EventFramework.sad").add(GlobalOutgoingConstraint("all", EventFramework, UserAPI))
        constraints("EventFramework.sad").add(GlobalOutgoingConstraint("all", EventFramework, DataTypes))
        constraints("EventFramework.sad").add(GlobalOutgoingConstraint("all", EventFramework, PropertySettings))
        constraints("EventFramework.sad").add(GlobalOutgoingConstraint("all", EventFramework, JDBCStatementProcessing))
        constraints("EventFramework.sad").add(GlobalOutgoingConstraint("all", EventFramework, Proxies))
        constraints("EventFramework.sad").add(GlobalOutgoingConstraint("all", EventFramework, Configuration))
        constraints("EventFramework.sad").add(GlobalOutgoingConstraint("all", EventFramework, HibernateClassic))
        constraints("EventFramework.sad").add(GlobalOutgoingConstraint("all", EventFramework, PersistenceManager))
        constraints("EventFramework.sad").add(GlobalOutgoingConstraint("all", EventFramework, IdentifierGenerators))
        constraints("EventFramework.sad").add(GlobalOutgoingConstraint("all", EventFramework, SessionManagement))
        constraints("EventFramework.sad").add(GlobalOutgoingConstraint("all", EventFramework, EntityRepresentation))
        constraints("EventFramework.sad").add(GlobalOutgoingConstraint("all", EventFramework, Statistics))
        constraints("EventFramework.sad").add(GlobalOutgoingConstraint("all", EventFramework, HibernateUtilities))
        constraints("EventFramework.sad").add(GlobalIncomingConstraint("all", SessionManagement, EventFramework))
        constraints("EventFramework.sad").add(GlobalIncomingConstraint("all", Configuration, EventFramework))
        constraints("EventFramework.sad").add(GlobalIncomingConstraint("all", SQLDialects, EventFramework))
        constraints("EventFramework.sad").add(GlobalIncomingConstraint("all", PersistenceManager, EventFramework))
        constraints("EventFramework.sad").add(GlobalIncomingConstraint("all", HQL, EventFramework))
        constraints("EventFramework.sad").add(GlobalIncomingConstraint("all", Actions, EventFramework))
        constraints("EventFramework.sad").add(GlobalIncomingConstraint("all", Cache, EventFramework))
        constraints("HandwrittenSQLLoader.sad")
                .add(GlobalIncomingConstraint("all", SessionManagement, HandwrittenSQLLoader))
        constraints("HandwrittenSQLLoader.sad").add(GlobalOutgoingConstraint("all", HandwrittenSQLLoader, UserAPI))
        constraints("HandwrittenSQLLoader.sad")
                .add(GlobalOutgoingConstraint("all", HandwrittenSQLLoader, SessionManagement))
        constraints("HandwrittenSQLLoader.sad")
                .add(GlobalOutgoingConstraint("all", HandwrittenSQLLoader, UtilitiesAndExceptions))
        constraints("HandwrittenSQLLoader.sad")
                .add(GlobalOutgoingConstraint("all", HandwrittenSQLLoader, PersistenceManager))
        constraints("HandwrittenSQLLoader.sad").add(GlobalOutgoingConstraint("all", HandwrittenSQLLoader, SQLDialects))
        constraints("HandwrittenSQLLoader.sad")
                .add(GlobalOutgoingConstraint("all", HandwrittenSQLLoader, ResultTransfomers))
        constraints("HandwrittenSQLLoader.sad").add(GlobalOutgoingConstraint("all", HandwrittenSQLLoader, DataTypes))
        constraints("HandwrittenSQLLoader.sad")
                .add(GlobalOutgoingConstraint("all", HandwrittenSQLLoader, SQLStatements))
        constraints("HandwrittenSQLLoader.sad")
                .add(GlobalOutgoingConstraint("all", HandwrittenSQLLoader, PropertySettings))
        constraints("HandwrittenSQLLoader.sad")
                .add(GlobalIncomingConstraint("all", SQLStatements, HandwrittenSQLLoader))
        constraints("HibernateClassic.sad").add(GlobalIncomingConstraint("all", SessionManagement, HibernateClassic))
        constraints("HibernateClassic.sad").add(GlobalOutgoingConstraint("all", HibernateClassic, UserAPI))
        constraints("HibernateClassic.sad").add(GlobalOutgoingConstraint("all", HibernateClassic, DataTypes))
        constraints("HibernateClassic.sad").add(GlobalOutgoingConstraint("all", HibernateClassic, SessionManagement))
        constraints("HibernateClassic.sad")
                .add(GlobalOutgoingConstraint("all", HibernateClassic, UtilitiesAndExceptions))
        constraints("HibernateClassic.sad").add(GlobalIncomingConstraint("all", EventFramework, HibernateClassic))
        constraints("HibernateClassic.sad").add(GlobalIncomingConstraint("all", JMX, HibernateClassic))
        constraints("HibernateCriteria.sad").add(GlobalIncomingConstraint("all", SessionManagement, HibernateCriteria))
        constraints("HibernateCriteria.sad").add(GlobalOutgoingConstraint("all", HibernateCriteria, ResultTransfomers))
        constraints("HibernateCriteria.sad")
                .add(GlobalOutgoingConstraint("all", HibernateCriteria, UtilitiesAndExceptions))
        constraints("HibernateCriteria.sad").add(GlobalOutgoingConstraint("all", HibernateCriteria, SessionManagement))
        constraints("HibernateCriteria.sad").add(GlobalOutgoingConstraint("all", HibernateCriteria, DataTypes))
        constraints("HibernateCriteria.sad")
                .add(GlobalOutgoingConstraint("all", HibernateCriteria, CriteriaExpressionFramework))
        constraints("HibernateCriteria.sad").add(GlobalOutgoingConstraint("all", HibernateCriteria, SQLDialects))
        constraints("HibernateCriteria.sad").add(GlobalOutgoingConstraint("all", HibernateCriteria, HibernateUtilities))
        constraints("HibernateCriteria.sad").add(GlobalOutgoingConstraint("all", HibernateCriteria, PersistenceManager))
        constraints("HibernateCriteria.sad").add(GlobalOutgoingConstraint("all", HibernateCriteria, UserAPI))
        constraints("HibernateCriteria.sad").add(GlobalOutgoingConstraint("all", HibernateCriteria, HQL))
        constraints("HibernateCriteria.sad").add(GlobalIncomingConstraint("all", UserAPI, HibernateCriteria))
        constraints("HibernateCriteria.sad")
                .add(GlobalIncomingConstraint("all", CriteriaExpressionFramework, HibernateCriteria))
        constraints("HibernateORMapping.sad")
                .add(GlobalIncomingConstraint("all", SessionManagement, HibernateORMapping))
        constraints("HibernateORMapping.sad")
                .add(GlobalIncomingConstraint("all", IdentifierGenerators, HibernateORMapping))
        constraints("HibernateORMapping.sad").add(GlobalIncomingConstraint("all", Configuration, HibernateORMapping))
        constraints("HibernateORMapping.sad")
                .add(GlobalIncomingConstraint("all", EntityRepresentation, HibernateORMapping))
        constraints("HibernateORMapping.sad").add(GlobalIncomingConstraint("all", SQLDialects, HibernateORMapping))
        constraints("HibernateORMapping.sad")
                .add(GlobalIncomingConstraint("all", PersistenceManager, HibernateORMapping))
        constraints("HibernateORMapping.sad").add(GlobalIncomingConstraint("all", SchemaProcessing, HibernateORMapping))
        constraints("HibernateORMapping.sad")
                .add(GlobalOutgoingConstraint("all", HibernateORMapping, PersistenceManager))
        constraints("HibernateORMapping.sad")
                .add(GlobalOutgoingConstraint("all", HibernateORMapping, UtilitiesAndExceptions))
        constraints("HibernateORMapping.sad").add(GlobalOutgoingConstraint("all", HibernateORMapping, SchemaProcessing))
        constraints("HibernateORMapping.sad")
                .add(GlobalOutgoingConstraint("all", HibernateORMapping, EntityRepresentation))
        constraints("HibernateORMapping.sad").add(GlobalOutgoingConstraint("all", HibernateORMapping, Configuration))
        constraints("HibernateORMapping.sad").add(GlobalOutgoingConstraint("all", HibernateORMapping, Annotations))
        constraints("HibernateORMapping.sad").add(GlobalOutgoingConstraint("all", HibernateORMapping, SQLDialects))
        constraints("HibernateORMapping.sad")
                .add(GlobalOutgoingConstraint("all", HibernateORMapping, SessionManagement))
        constraints("HibernateORMapping.sad")
                .add(GlobalOutgoingConstraint("all", HibernateORMapping, HibernateUtilities))
        constraints("HibernateORMapping.sad").add(GlobalOutgoingConstraint("all", HibernateORMapping, Properties))
        constraints("HibernateORMapping.sad").add(GlobalOutgoingConstraint("all", HibernateORMapping, DataTypes))
        constraints("HibernateORMapping.sad").add(GlobalOutgoingConstraint("all", HibernateORMapping, SQLStatements))
        constraints("HibernateORMapping.sad")
                .add(GlobalOutgoingConstraint("all", HibernateORMapping, IdentifierGenerators))
        constraints("HibernateORMapping.sad").add(GlobalIncomingConstraint("all", Properties, HibernateORMapping))
        constraints("HibernateORMapping.sad").add(GlobalIncomingConstraint("all", Cache, HibernateORMapping))
        constraints("HibernateORMapping.sad").add(GlobalIncomingConstraint("all", DataTypes, HibernateORMapping))
        constraints("HibernateUtilities.sad")
                .add(GlobalIncomingConstraint("all", HibernateCriteria, HibernateUtilities))
        constraints("HibernateUtilities.sad")
                .add(GlobalIncomingConstraint("all", IdentifierGenerators, HibernateUtilities))
        constraints("HibernateUtilities.sad")
                .add(GlobalIncomingConstraint("all", EntityRepresentation, HibernateUtilities))
        constraints("HibernateUtilities.sad").add(GlobalIncomingConstraint("all", JMX, HibernateUtilities))
        constraints("HibernateUtilities.sad")
                .add(GlobalIncomingConstraint("all", HibernateORMapping, HibernateUtilities))
        constraints("HibernateUtilities.sad")
                .add(GlobalIncomingConstraint("all", UtilitiesAndExceptions, HibernateUtilities))
        constraints("HibernateUtilities.sad").add(GlobalIncomingConstraint("all", SQLStatements, HibernateUtilities))
        constraints("HibernateUtilities.sad").add(GlobalIncomingConstraint("all", EventFramework, HibernateUtilities))
        constraints("HibernateUtilities.sad").add(GlobalOutgoingConstraint("all", HibernateUtilities, UserAPI))
        constraints("HibernateUtilities.sad")
                .add(GlobalOutgoingConstraint("all", HibernateUtilities, PersistenceManager))
        constraints("HibernateUtilities.sad")
                .add(GlobalOutgoingConstraint("all", HibernateUtilities, IdentifierGenerators))
        constraints("HibernateUtilities.sad").add(GlobalOutgoingConstraint("all", HibernateUtilities, DataTypes))
        constraints("HibernateUtilities.sad")
                .add(GlobalOutgoingConstraint("all", HibernateUtilities, SessionManagement))
        constraints("HibernateUtilities.sad").add(GlobalOutgoingConstraint("all", HibernateUtilities, SQLStatements))
        constraints("HibernateUtilities.sad").add(GlobalOutgoingConstraint("all", HibernateUtilities, Metadata))
        constraints("HibernateUtilities.sad").add(GlobalOutgoingConstraint("all", HibernateUtilities, Properties))
        constraints("HibernateUtilities.sad").add(GlobalOutgoingConstraint("all", HibernateUtilities, Configuration))
        constraints("HibernateUtilities.sad")
                .add(GlobalOutgoingConstraint("all", HibernateUtilities, UtilitiesAndExceptions))
        constraints("HibernateUtilities.sad")
                .add(GlobalOutgoingConstraint("all", HibernateUtilities, BytecodeInterception))
        constraints("HibernateUtilities.sad").add(GlobalOutgoingConstraint("all", HibernateUtilities, PropertySettings))
        constraints("HibernateUtilities.sad")
                .add(GlobalIncomingConstraint("all", SessionManagement, HibernateUtilities))
        constraints("HibernateUtilities.sad").add(GlobalIncomingConstraint("all", Configuration, HibernateUtilities))
        constraints("HibernateUtilities.sad").add(GlobalIncomingConstraint("all", SQLDialects, HibernateUtilities))
        constraints("HibernateUtilities.sad")
                .add(GlobalIncomingConstraint("all", PersistenceManager, HibernateUtilities))
        constraints("HibernateUtilities.sad").add(GlobalIncomingConstraint("all", UserAPI, HibernateUtilities))
        constraints("HibernateUtilities.sad").add(GlobalIncomingConstraint("all", HQL, HibernateUtilities))
        constraints("HibernateUtilities.sad").add(GlobalIncomingConstraint("all", Actions, HibernateUtilities))
        constraints("HibernateUtilities.sad").add(GlobalIncomingConstraint("all", Cache, HibernateUtilities))
        constraints("HQL_Legacy.sad").add(GlobalOutgoingConstraint("all", HQL_Legacy, ResultTransfomers))
        constraints("HQL_Legacy.sad").add(GlobalOutgoingConstraint("all", HQL_Legacy, HQL))
        constraints("HQL_Legacy.sad").add(GlobalOutgoingConstraint("all", HQL_Legacy, SessionManagement))
        constraints("HQL_Legacy.sad").add(GlobalOutgoingConstraint("all", HQL_Legacy, SQLDialects))
        constraints("HQL_Legacy.sad").add(GlobalOutgoingConstraint("all", HQL_Legacy, EventFramework))
        constraints("HQL_Legacy.sad").add(GlobalOutgoingConstraint("all", HQL_Legacy, PersistenceManager))
        constraints("HQL_Legacy.sad").add(GlobalOutgoingConstraint("all", HQL_Legacy, UserAPI))
        constraints("HQL_Legacy.sad").add(GlobalOutgoingConstraint("all", HQL_Legacy, Statistics))
        constraints("HQL_Legacy.sad").add(GlobalOutgoingConstraint("all", HQL_Legacy, DataTypes))
        constraints("HQL_Legacy.sad").add(GlobalOutgoingConstraint("all", HQL_Legacy, UtilitiesAndExceptions))
        constraints("HQL_Legacy.sad").add(GlobalIncomingConstraint("all", HQL, HQL_Legacy))
        constraints("HQL.sad").add(GlobalIncomingConstraint("all", SessionManagement, HQL))
        constraints("HQL.sad").add(GlobalIncomingConstraint("all", HibernateCriteria, HQL))
        constraints("HQL.sad").add(GlobalIncomingConstraint("all", SQLDialects, HQL))
        constraints("HQL.sad").add(GlobalIncomingConstraint("all", PropertySettings, HQL))
        constraints("HQL.sad").add(GlobalIncomingConstraint("all", SQLStatements, HQL))
        constraints("HQL.sad").add(GlobalIncomingConstraint("all", HQL_Legacy, HQL))
        constraints("HQL.sad").add(GlobalOutgoingConstraint("all", HQL, SessionManagement))
        constraints("HQL.sad").add(GlobalOutgoingConstraint("all", HQL, EventFramework))
        constraints("HQL.sad").add(GlobalOutgoingConstraint("all", HQL, UtilitiesAndExceptions))
        constraints("HQL.sad").add(GlobalOutgoingConstraint("all", HQL, Actions))
        constraints("HQL.sad").add(GlobalOutgoingConstraint("all", HQL, UserAPI))
        constraints("HQL.sad").add(GlobalOutgoingConstraint("all", HQL, DataTypes))
        constraints("HQL.sad").add(GlobalOutgoingConstraint("all", HQL, Statistics))
        constraints("HQL.sad").add(GlobalOutgoingConstraint("all", HQL, JDBCStatementProcessing))
        constraints("HQL.sad").add(GlobalOutgoingConstraint("all", HQL, PropertySettings))
        constraints("HQL.sad").add(GlobalOutgoingConstraint("all", HQL, EntityRepresentation))
        constraints("HQL.sad").add(GlobalOutgoingConstraint("all", HQL, Transactions))
        constraints("HQL.sad").add(GlobalOutgoingConstraint("all", HQL, SQLStatements))
        constraints("HQL.sad").add(GlobalOutgoingConstraint("all", HQL, ResultTransfomers))
        constraints("HQL.sad").add(GlobalOutgoingConstraint("all", HQL, IdentifierGenerators))
        constraints("HQL.sad").add(GlobalOutgoingConstraint("all", HQL, HQL_Legacy))
        constraints("HQL.sad").add(GlobalOutgoingConstraint("all", HQL, HibernateUtilities))
        constraints("HQL.sad").add(GlobalOutgoingConstraint("all", HQL, PersistenceManager))
        constraints("HQL.sad").add(GlobalOutgoingConstraint("all", HQL, SQLDialects))
        constraints("IdentifierGenerators.sad")
                .add(GlobalIncomingConstraint("all", SessionManagement, IdentifierGenerators))
        constraints("IdentifierGenerators.sad").add(GlobalOutgoingConstraint("all", IdentifierGenerators, UserAPI))
        constraints("IdentifierGenerators.sad")
                .add(GlobalOutgoingConstraint("all", IdentifierGenerators, SQLStatements))
        constraints("IdentifierGenerators.sad")
                .add(GlobalOutgoingConstraint("all", IdentifierGenerators, HibernateORMapping))
        constraints("IdentifierGenerators.sad").add(GlobalOutgoingConstraint("all", IdentifierGenerators, DataTypes))
        constraints("IdentifierGenerators.sad")
                .add(GlobalOutgoingConstraint("all", IdentifierGenerators, PersistenceManager))
        constraints("IdentifierGenerators.sad")
                .add(GlobalOutgoingConstraint("all", IdentifierGenerators, HibernateUtilities))
        constraints("IdentifierGenerators.sad").add(GlobalOutgoingConstraint("all", IdentifierGenerators, SQLDialects))
        constraints("IdentifierGenerators.sad")
                .add(GlobalOutgoingConstraint("all", IdentifierGenerators, UtilitiesAndExceptions))
        constraints("IdentifierGenerators.sad")
                .add(GlobalOutgoingConstraint("all", IdentifierGenerators, JDBCStatementProcessing))
        constraints("IdentifierGenerators.sad").add(GlobalOutgoingConstraint("all", IdentifierGenerators, Transactions))
        constraints("IdentifierGenerators.sad")
                .add(GlobalOutgoingConstraint("all", IdentifierGenerators, SessionManagement))
        constraints("IdentifierGenerators.sad")
                .add(GlobalIncomingConstraint("all", Configuration, IdentifierGenerators))
        constraints("IdentifierGenerators.sad")
                .add(GlobalIncomingConstraint("all", EntityRepresentation, IdentifierGenerators))
        constraints("IdentifierGenerators.sad")
                .add(GlobalIncomingConstraint("all", PersistenceManager, IdentifierGenerators))
        constraints("IdentifierGenerators.sad").add(GlobalIncomingConstraint("all", JMX, IdentifierGenerators))
        constraints("IdentifierGenerators.sad")
                .add(GlobalIncomingConstraint("all", HibernateORMapping, IdentifierGenerators))
        constraints("IdentifierGenerators.sad").add(GlobalIncomingConstraint("all", HQL, IdentifierGenerators))
        constraints("IdentifierGenerators.sad")
                .add(GlobalIncomingConstraint("all", EventFramework, IdentifierGenerators))
        constraints("IdentifierGenerators.sad")
                .add(GlobalIncomingConstraint("all", HibernateUtilities, IdentifierGenerators))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalIncomingConstraint("all", SessionManagement, JDBCStatementProcessing))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalIncomingConstraint("all", IdentifierGenerators, JDBCStatementProcessing))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalIncomingConstraint("all", SQLDialects, JDBCStatementProcessing))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalIncomingConstraint("all", PropertySettings, JDBCStatementProcessing))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalIncomingConstraint("all", PersistenceManager, JDBCStatementProcessing))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalIncomingConstraint("all", SchemaProcessing, JDBCStatementProcessing))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalIncomingConstraint("all", SQLStatements, JDBCStatementProcessing))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalOutgoingConstraint("all", JDBCStatementProcessing, UserAPI))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalOutgoingConstraint("all", JDBCStatementProcessing, Statistics))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalOutgoingConstraint("all", JDBCStatementProcessing, ConnectionProvider))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalOutgoingConstraint("all", JDBCStatementProcessing, UtilitiesAndExceptions))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalOutgoingConstraint("all", JDBCStatementProcessing, SessionManagement))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalOutgoingConstraint("all", JDBCStatementProcessing, DataTypes))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalOutgoingConstraint("all", JDBCStatementProcessing, DeprecatedUtility))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalOutgoingConstraint("all", JDBCStatementProcessing, PropertySettings))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalOutgoingConstraint("all", JDBCStatementProcessing, SQLDialects))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalIncomingConstraint("all", UserAPI, JDBCStatementProcessing))
        constraints("JDBCStatementProcessing.sad").add(GlobalIncomingConstraint("all", HQL, JDBCStatementProcessing))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalIncomingConstraint("all", Transactions, JDBCStatementProcessing))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalIncomingConstraint("all", Actions, JDBCStatementProcessing))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalIncomingConstraint("all", EventFramework, JDBCStatementProcessing))
        constraints("JDBCStatementProcessing.sad")
                .add(GlobalIncomingConstraint("all", DataTypes, JDBCStatementProcessing))
        constraints("JMX.sad").add(GlobalIncomingConstraint("all", EmptyEnsemble, JMX))
        constraints("Metadata.sad").add(GlobalOutgoingConstraint("all", Metadata, SessionManagement))
        constraints("Metadata.sad").add(GlobalOutgoingConstraint("all", Metadata, DataTypes))
        constraints("Metadata.sad").add(GlobalOutgoingConstraint("all", Metadata, UtilitiesAndExceptions))
        constraints("Properties.sad").add(GlobalOutgoingConstraint("all", Properties, PersistenceManager))
        constraints("Properties.sad").add(GlobalOutgoingConstraint("all", Properties, UtilitiesAndExceptions))
        constraints("Properties.sad").add(GlobalOutgoingConstraint("all", Properties, HibernateORMapping))
        constraints("Properties.sad").add(GlobalOutgoingConstraint("all", Properties, SessionManagement))
        constraints("Properties.sad").add(GlobalOutgoingConstraint("all", Properties, DataTypes))
        constraints("Properties.sad").add(GlobalIncomingConstraint("all", EntityRepresentation, Properties))
        constraints("Properties.sad").add(GlobalIncomingConstraint("all", HibernateUtilities, Properties))
        constraints("Properties.sad").add(GlobalIncomingConstraint("all", PersistenceManager, Properties))
        constraints("Properties.sad").add(GlobalIncomingConstraint("all", ResultTransfomers, Properties))
        constraints("Properties.sad").add(GlobalIncomingConstraint("all", HibernateORMapping, Properties))
        constraints("Properties.sad").add(GlobalIncomingConstraint("all", UtilitiesAndExceptions, Properties))
        constraints("Properties.sad").add(GlobalIncomingConstraint("all", DataTypes, Properties))
        constraints("PropertySettings.sad").add(GlobalIncomingConstraint("all", EntityRepresentation, PropertySettings))
        constraints("PropertySettings.sad").add(GlobalOutgoingConstraint("all", PropertySettings, Cache))
        constraints("PropertySettings.sad")
                .add(GlobalOutgoingConstraint("all", PropertySettings, UtilitiesAndExceptions))
        constraints("PropertySettings.sad").add(GlobalOutgoingConstraint("all", PropertySettings, EntityRepresentation))
        constraints("PropertySettings.sad").add(GlobalOutgoingConstraint("all", PropertySettings, Transactions))
        constraints("PropertySettings.sad")
                .add(GlobalOutgoingConstraint("all", PropertySettings, BytecodeInstrumentation))
        constraints("PropertySettings.sad").add(GlobalOutgoingConstraint("all", PropertySettings, UserAPI))
        constraints("PropertySettings.sad").add(GlobalOutgoingConstraint("all", PropertySettings, ConnectionProvider))
        constraints("PropertySettings.sad").add(GlobalOutgoingConstraint("all", PropertySettings, HQL))
        constraints("PropertySettings.sad").add(GlobalOutgoingConstraint("all", PropertySettings, SQLDialects))
        constraints("PropertySettings.sad")
                .add(GlobalOutgoingConstraint("all", PropertySettings, JDBCStatementProcessing))
        constraints("PropertySettings.sad")
                .add(GlobalIncomingConstraint("all", JDBCStatementProcessing, PropertySettings))
        constraints("PropertySettings.sad").add(GlobalIncomingConstraint("all", EventFramework, PropertySettings))
        constraints("PropertySettings.sad").add(GlobalIncomingConstraint("all", HibernateUtilities, PropertySettings))
        constraints("PropertySettings.sad").add(GlobalIncomingConstraint("all", HandwrittenSQLLoader, PropertySettings))
        constraints("PropertySettings.sad").add(GlobalIncomingConstraint("all", DataTypes, PropertySettings))
        constraints("PropertySettings.sad").add(GlobalIncomingConstraint("all", SessionManagement, PropertySettings))
        constraints("PropertySettings.sad").add(GlobalIncomingConstraint("all", ConnectionProvider, PropertySettings))
        constraints("PropertySettings.sad").add(GlobalIncomingConstraint("all", Configuration, PropertySettings))
        constraints("PropertySettings.sad").add(GlobalIncomingConstraint("all", SQLDialects, PropertySettings))
        constraints("PropertySettings.sad").add(GlobalIncomingConstraint("all", PersistenceManager, PropertySettings))
        constraints("PropertySettings.sad").add(GlobalIncomingConstraint("all", SchemaProcessing, PropertySettings))
        constraints("PropertySettings.sad").add(GlobalIncomingConstraint("all", UserAPI, PropertySettings))
        constraints("PropertySettings.sad").add(GlobalIncomingConstraint("all", HQL, PropertySettings))
        constraints("PropertySettings.sad").add(GlobalIncomingConstraint("all", Actions, PropertySettings))
        constraints("PropertySettings.sad").add(GlobalIncomingConstraint("all", Cache, PropertySettings))
        constraints("Proxies.sad").add(GlobalIncomingConstraint("all", SessionManagement, Proxies))
        constraints("Proxies.sad").add(GlobalIncomingConstraint("all", BytecodeInstrumentation, Proxies))
        constraints("Proxies.sad").add(GlobalIncomingConstraint("all", Configuration, Proxies))
        constraints("Proxies.sad").add(GlobalIncomingConstraint("all", EntityRepresentation, Proxies))
        constraints("Proxies.sad").add(GlobalIncomingConstraint("all", BytecodeInterception, Proxies))
        constraints("Proxies.sad").add(GlobalIncomingConstraint("all", PersistenceManager, Proxies))
        constraints("Proxies.sad").add(GlobalOutgoingConstraint("all", Proxies, PersistenceManager))
        constraints("Proxies.sad").add(GlobalOutgoingConstraint("all", Proxies, DataTypes))
        constraints("Proxies.sad").add(GlobalOutgoingConstraint("all", Proxies, UtilitiesAndExceptions))
        constraints("Proxies.sad").add(GlobalOutgoingConstraint("all", Proxies, SessionManagement))
        constraints("Proxies.sad").add(GlobalIncomingConstraint("all", UserAPI, Proxies))
        constraints("Proxies.sad").add(GlobalIncomingConstraint("all", EventFramework, Proxies))
        constraints("Proxies.sad").add(GlobalIncomingConstraint("all", DataTypes, Proxies))
        constraints("ResultTransfomers.sad").add(GlobalIncomingConstraint("all", HQL_Legacy, ResultTransfomers))
        constraints("ResultTransfomers.sad").add(GlobalIncomingConstraint("all", HibernateCriteria, ResultTransfomers))
        constraints("ResultTransfomers.sad").add(GlobalIncomingConstraint("all", UserAPI, ResultTransfomers))
        constraints("ResultTransfomers.sad").add(GlobalIncomingConstraint("all", HQL, ResultTransfomers))
        constraints("ResultTransfomers.sad")
                .add(GlobalIncomingConstraint("all", CriteriaExpressionFramework, ResultTransfomers))
        constraints("ResultTransfomers.sad").add(GlobalIncomingConstraint("all", PersistenceManager, ResultTransfomers))
        constraints("ResultTransfomers.sad")
                .add(GlobalIncomingConstraint("all", HandwrittenSQLLoader, ResultTransfomers))
        constraints("ResultTransfomers.sad")
                .add(GlobalOutgoingConstraint("all", ResultTransfomers, UtilitiesAndExceptions))
        constraints("ResultTransfomers.sad").add(GlobalOutgoingConstraint("all", ResultTransfomers, Properties))
        constraints("ResultTransfomers.sad").add(GlobalIncomingConstraint("all", Cache, ResultTransfomers))
        constraints("SchemaProcessing.sad").add(GlobalOutgoingConstraint("all", SchemaProcessing, SQLDialects))
        constraints("SchemaProcessing.sad").add(GlobalOutgoingConstraint("all", SchemaProcessing, Configuration))
        constraints("SchemaProcessing.sad")
                .add(GlobalOutgoingConstraint("all", SchemaProcessing, JDBCStatementProcessing))
        constraints("SchemaProcessing.sad").add(GlobalOutgoingConstraint("all", SchemaProcessing, ConnectionProvider))
        constraints("SchemaProcessing.sad")
                .add(GlobalOutgoingConstraint("all", SchemaProcessing, UtilitiesAndExceptions))
        constraints("SchemaProcessing.sad").add(GlobalOutgoingConstraint("all", SchemaProcessing, PropertySettings))
        constraints("SchemaProcessing.sad").add(GlobalOutgoingConstraint("all", SchemaProcessing, HibernateORMapping))
        constraints("SchemaTool.sad").add(GlobalIncomingConstraint("all", EmptyEnsemble, SchemaTool))
        constraints("SchemaTool.sad").add(GlobalOutgoingConstraint("all", SchemaTool, UtilitiesAndExceptions))
        constraints("SchemaTool.sad").add(GlobalOutgoingConstraint("all", SchemaTool, SchemaProcessing))
        constraints("SchemaTool.sad").add(GlobalOutgoingConstraint("all", SchemaTool, Configuration))
        constraints("SecurityPolicy.sad").add(GlobalOutgoingConstraint("all", SecurityPolicy, EventFramework))
        constraints("SecurityPolicy.sad").add(GlobalOutgoingConstraint("all", SecurityPolicy, Configuration))
        constraints("SecurityPolicy.sad").add(GlobalOutgoingConstraint("all", SecurityPolicy, UtilitiesAndExceptions))
        constraints("SecurityPolicy.sad").add(GlobalOutgoingConstraint("all", SecurityPolicy, PersistenceManager))
        constraints("SecurityPolicy.sad").add(GlobalIncomingConstraint("all", Configuration, SecurityPolicy))
        constraints("SQLDialects.sad").add(GlobalIncomingConstraint("all", HibernateCriteria, SQLDialects))
        constraints("SQLDialects.sad").add(GlobalIncomingConstraint("all", IdentifierGenerators, SQLDialects))
        constraints("SQLDialects.sad").add(GlobalIncomingConstraint("all", PropertySettings, SQLDialects))
        constraints("SQLDialects.sad").add(GlobalIncomingConstraint("all", HibernateORMapping, SQLDialects))
        constraints("SQLDialects.sad").add(GlobalIncomingConstraint("all", UtilitiesAndExceptions, SQLDialects))
        constraints("SQLDialects.sad").add(GlobalIncomingConstraint("all", SQLStatements, SQLDialects))
        constraints("SQLDialects.sad").add(GlobalIncomingConstraint("all", HQL_Legacy, SQLDialects))
        constraints("SQLDialects.sad").add(GlobalIncomingConstraint("all", JDBCStatementProcessing, SQLDialects))
        constraints("SQLDialects.sad").add(GlobalIncomingConstraint("all", HandwrittenSQLLoader, SQLDialects))
        constraints("SQLDialects.sad").add(GlobalIncomingConstraint("all", DataTypes, SQLDialects))
        constraints("SQLDialects.sad").add(GlobalIncomingConstraint("all", SessionManagement, SQLDialects))
        constraints("SQLDialects.sad").add(GlobalIncomingConstraint("all", Configuration, SQLDialects))
        constraints("SQLDialects.sad").add(GlobalOutgoingConstraint("all", SQLDialects, PersistenceManager))
        constraints("SQLDialects.sad").add(GlobalOutgoingConstraint("all", SQLDialects, HQL))
        constraints("SQLDialects.sad").add(GlobalOutgoingConstraint("all", SQLDialects, Actions))
        constraints("SQLDialects.sad").add(GlobalOutgoingConstraint("all", SQLDialects, SQLStatements))
        constraints("SQLDialects.sad").add(GlobalOutgoingConstraint("all", SQLDialects, UserAPI))
        constraints("SQLDialects.sad").add(GlobalOutgoingConstraint("all", SQLDialects, UtilitiesAndExceptions))
        constraints("SQLDialects.sad").add(GlobalOutgoingConstraint("all", SQLDialects, Statistics))
        constraints("SQLDialects.sad").add(GlobalOutgoingConstraint("all", SQLDialects, JDBCStatementProcessing))
        constraints("SQLDialects.sad").add(GlobalOutgoingConstraint("all", SQLDialects, EventFramework))
        constraints("SQLDialects.sad").add(GlobalOutgoingConstraint("all", SQLDialects, SessionManagement))
        constraints("SQLDialects.sad").add(GlobalOutgoingConstraint("all", SQLDialects, DataTypes))
        constraints("SQLDialects.sad").add(GlobalOutgoingConstraint("all", SQLDialects, PropertySettings))
        constraints("SQLDialects.sad").add(GlobalOutgoingConstraint("all", SQLDialects, HibernateUtilities))
        constraints("SQLDialects.sad").add(GlobalOutgoingConstraint("all", SQLDialects, HibernateORMapping))
        constraints("SQLDialects.sad").add(GlobalIncomingConstraint("all", PersistenceManager, SQLDialects))
        constraints("SQLDialects.sad").add(GlobalIncomingConstraint("all", SchemaProcessing, SQLDialects))
        constraints("SQLDialects.sad").add(GlobalIncomingConstraint("all", HQL, SQLDialects))
        constraints("SQLDialects.sad").add(GlobalIncomingConstraint("all", CriteriaExpressionFramework, SQLDialects))
        constraints("SQLStatements.sad").add(GlobalIncomingConstraint("all", SessionManagement, SQLStatements))
        constraints("SQLStatements.sad").add(GlobalIncomingConstraint("all", IdentifierGenerators, SQLStatements))
        constraints("SQLStatements.sad").add(GlobalIncomingConstraint("all", Configuration, SQLStatements))
        constraints("SQLStatements.sad").add(GlobalIncomingConstraint("all", SQLDialects, SQLStatements))
        constraints("SQLStatements.sad").add(GlobalIncomingConstraint("all", PersistenceManager, SQLStatements))
        constraints("SQLStatements.sad").add(GlobalIncomingConstraint("all", HibernateORMapping, SQLStatements))
        constraints("SQLStatements.sad").add(GlobalOutgoingConstraint("all", SQLStatements, SessionManagement))
        constraints("SQLStatements.sad").add(GlobalOutgoingConstraint("all", SQLStatements, PersistenceManager))
        constraints("SQLStatements.sad").add(GlobalOutgoingConstraint("all", SQLStatements, DataTypes))
        constraints("SQLStatements.sad").add(GlobalOutgoingConstraint("all", SQLStatements, HibernateUtilities))
        constraints("SQLStatements.sad").add(GlobalOutgoingConstraint("all", SQLStatements, HQL))
        constraints("SQLStatements.sad").add(GlobalOutgoingConstraint("all", SQLStatements, SQLDialects))
        constraints("SQLStatements.sad").add(GlobalOutgoingConstraint("all", SQLStatements, UserAPI))
        constraints("SQLStatements.sad").add(GlobalOutgoingConstraint("all", SQLStatements, Actions))
        constraints("SQLStatements.sad").add(GlobalOutgoingConstraint("all", SQLStatements, EventFramework))
        constraints("SQLStatements.sad").add(GlobalOutgoingConstraint("all", SQLStatements, JDBCStatementProcessing))
        constraints("SQLStatements.sad").add(GlobalOutgoingConstraint("all", SQLStatements, UtilitiesAndExceptions))
        constraints("SQLStatements.sad").add(GlobalOutgoingConstraint("all", SQLStatements, HandwrittenSQLLoader))
        constraints("SQLStatements.sad").add(GlobalIncomingConstraint("all", UserAPI, SQLStatements))
        constraints("SQLStatements.sad").add(GlobalIncomingConstraint("all", HQL, SQLStatements))
        constraints("SQLStatements.sad").add(GlobalIncomingConstraint("all", HibernateUtilities, SQLStatements))
        constraints("SQLStatements.sad").add(GlobalIncomingConstraint("all", HandwrittenSQLLoader, SQLStatements))
        constraints("Statistics.sad").add(GlobalIncomingConstraint("all", SessionManagement, Statistics))
        constraints("Statistics.sad").add(GlobalIncomingConstraint("all", SQLDialects, Statistics))
        constraints("Statistics.sad").add(GlobalIncomingConstraint("all", PersistenceManager, Statistics))
        constraints("Statistics.sad").add(GlobalIncomingConstraint("all", JMX, Statistics))
        constraints("Statistics.sad").add(GlobalIncomingConstraint("all", HQL_Legacy, Statistics))
        constraints("Statistics.sad").add(GlobalIncomingConstraint("all", JDBCStatementProcessing, Statistics))
        constraints("Statistics.sad").add(GlobalOutgoingConstraint("all", Statistics, UtilitiesAndExceptions))
        constraints("Statistics.sad").add(GlobalOutgoingConstraint("all", Statistics, DataTypes))
        constraints("Statistics.sad").add(GlobalOutgoingConstraint("all", Statistics, Cache))
        constraints("Statistics.sad").add(GlobalOutgoingConstraint("all", Statistics, PersistenceManager))
        constraints("Statistics.sad").add(GlobalOutgoingConstraint("all", Statistics, SessionManagement))
        constraints("Statistics.sad").add(GlobalIncomingConstraint("all", HQL, Statistics))
        constraints("Statistics.sad").add(GlobalIncomingConstraint("all", EventFramework, Statistics))
        constraints("Statistics.sad").add(GlobalIncomingConstraint("all", Actions, Statistics))
        constraints("Transactions.sad").add(GlobalIncomingConstraint("all", SessionManagement, Transactions))
        constraints("Transactions.sad").add(GlobalIncomingConstraint("all", IdentifierGenerators, Transactions))
        constraints("Transactions.sad").add(GlobalIncomingConstraint("all", UserAPI, Transactions))
        constraints("Transactions.sad").add(GlobalIncomingConstraint("all", HQL, Transactions))
        constraints("Transactions.sad").add(GlobalIncomingConstraint("all", PropertySettings, Transactions))
        constraints("Transactions.sad").add(GlobalOutgoingConstraint("all", Transactions, ConnectionProvider))
        constraints("Transactions.sad").add(GlobalOutgoingConstraint("all", Transactions, JDBCStatementProcessing))
        constraints("Transactions.sad").add(GlobalOutgoingConstraint("all", Transactions, UtilitiesAndExceptions))
        constraints("Transactions.sad").add(GlobalOutgoingConstraint("all", Transactions, SessionManagement))
        constraints("UtilitiesAndExceptions.sad")
                .add(GlobalOutgoingConstraint("all", UtilitiesAndExceptions, Properties))
        constraints("UtilitiesAndExceptions.sad")
                .add(GlobalOutgoingConstraint("all", UtilitiesAndExceptions, SessionManagement))
        constraints("UtilitiesAndExceptions.sad")
                .add(GlobalOutgoingConstraint("all", UtilitiesAndExceptions, DataTypes))
        constraints("UtilitiesAndExceptions.sad")
                .add(GlobalOutgoingConstraint("all", UtilitiesAndExceptions, HibernateUtilities))
        constraints("UtilitiesAndExceptions.sad")
                .add(GlobalOutgoingConstraint("all", UtilitiesAndExceptions, SQLDialects))
        constraints("UtilitiesAndExceptions.sad")
                .add(GlobalOutgoingConstraint("all", UtilitiesAndExceptions, Configuration))
        constraints("UtilitiesAndExceptions.sad")
                .add(GlobalOutgoingConstraint("all", UtilitiesAndExceptions, PersistenceManager))
        constraints("UtilitiesAndExceptions.sad").add(GlobalOutgoingConstraint("all", UtilitiesAndExceptions, UserAPI))

    }

}